analyzer:
  exclude:
    - build/**
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - public_member_api_docs
    - prefer_const_constructors
    - prefer_final_locals
    - unawaited_futures
